site_name: Duduf After Effects Framework
site_url: https://rainboxprod.coop
repo_url: https://github.com/Rainbox-dev/DuAEF_Duik/
edit_uri: edit/master/src-docs/duaef/docs/
site_description: The Duduf After Effects Framework comprehensive documentation
site_author: Nicolas Dufresne and contributors
copyright: 'Copyright Â© 2018 Rainbox Productions and Nicolas Dufresne'
theme:
    name: readthedocs
    custom_dir: theme/
markdown_extensions:
    - smarty
    - footnotes
    - tables
    - admonition
    - codehilite
    - fenced_code
    - toc
extra_css:
    - style.css
dev_addr: '127.0.0.1:8000'
nav:
    - About: index.md
    - Tools:
        - Duben - Benchmark: ""
        - Dugr - Layer groups: ""
        - Duframe - Framing guides: ""
        - Duik - Rigging & animation: https://rainbox-dev.github.io/DuAEF_Duik/Guides/Duik/
        - Krita - Import Krita animations: ""
        - WUStoryboarder - Import Storyboarder files: ""
    - Contribution:
        - Contributing guide: contributing-guide.md
        - Documentation: documentation.md
        - Translation: translation.md
        - Bug Report & Feature Request: bug-report-&-feature-request.md
        - Development: coding.md
        - Code guidelines: code-guidelines.md
        - Donation: donation.md
        - Duduf on Patreon: https://patreon.com/duduf
    - Developper guide:
        - How to use DuAEF: how-to.md
        - The Framework reference: https://rainbox-dev.github.io/DuAEF_Duik/Framework-Reference/
    - License: license.md
    - Contact: contact.md
    - Credits: credits.md
